name: Cypress Tests

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0' 

      - name: Uninstall dependencies
        run: npm uninstall cypress

      - name: Install dependencies
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npx cypress run   

     